scons: Reading SConscript files ...
trying egglib import vplants.tool
Loading qt4 tool...
scons: done reading SConscript files.
scons: Building targets ...
scons: building associated VariantDir targets: build-scons
g++ -o build-scons/src/cpp/categorical_process.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -DDEBUG -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/cpp/categorical_process.cpp
g++ -o build-scons/src/cpp/regression.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -DDEBUG -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/cpp/regression.cpp
g++ -o build-scons/src/cpp/compound.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -DDEBUG -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/cpp/compound.cpp
g++ -o build-scons/src/cpp/stat_label.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -DDEBUG -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/cpp/stat_label.cpp
g++ -o build-scons/src/cpp/mixture_algorithms.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -DDEBUG -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/cpp/mixture_algorithms.cpp
g++ -o build-scons/src/cpp/distribution.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -DDEBUG -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/cpp/distribution.cpp
g++ -o build-scons/src/cpp/test.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -DDEBUG -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/cpp/test.cpp
g++ -o build-scons/src/cpp/distance_matrix.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -DDEBUG -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/cpp/distance_matrix.cpp
g++ -o build-scons/src/cpp/chain.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -DDEBUG -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/cpp/chain.cpp
g++ -o build-scons/src/cpp/vector_algorithms.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -DDEBUG -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/cpp/vector_algorithms.cpp
g++ -o build-scons/src/cpp/vectors.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -DDEBUG -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/cpp/vectors.cpp
g++ -o build-scons/src/cpp/compound_algorithms.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -DDEBUG -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/cpp/compound_algorithms.cpp
g++ -o build-scons/src/cpp/curves.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -DDEBUG -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/cpp/curves.cpp
g++ -o build-scons/src/cpp/continuous_parametric.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -DDEBUG -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/cpp/continuous_parametric.cpp
g++ -o build-scons/src/cpp/discrete_parametric_process.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -DDEBUG -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/cpp/discrete_parametric_process.cpp
g++ -o build-scons/src/cpp/convolution_algorithms.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -DDEBUG -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/cpp/convolution_algorithms.cpp
g++ -o build-scons/src/cpp/distribution_algorithms.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -DDEBUG -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/cpp/distribution_algorithms.cpp
g++ -o build-scons/src/cpp/discrete_mixture_algorithms.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -DDEBUG -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/cpp/discrete_mixture_algorithms.cpp
g++ -o build-scons/src/cpp/multivariate_mixture.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -DDEBUG -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/cpp/multivariate_mixture.cpp
g++ -o build-scons/src/cpp/mixture.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -DDEBUG -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/cpp/mixture.cpp
g++ -o build-scons/src/cpp/multivariate_mixture_algorithms.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -DDEBUG -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/cpp/multivariate_mixture_algorithms.cpp
g++ -o build-scons/src/cpp/dendrogram.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -DDEBUG -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/cpp/dendrogram.cpp
g++ -o build-scons/src/cpp/clusters.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -DDEBUG -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/cpp/clusters.cpp
g++ -o build-scons/src/cpp/frequency_distribution2.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -DDEBUG -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/cpp/frequency_distribution2.cpp
g++ -o build-scons/src/cpp/chain_algorithms.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -DDEBUG -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/cpp/chain_algorithms.cpp
g++ -o build-scons/src/cpp/discrete_mixture.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -DDEBUG -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/cpp/discrete_mixture.cpp
g++ -o build-scons/src/cpp/frequency_distribution1.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -DDEBUG -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/cpp/frequency_distribution1.cpp
g++ -o build-scons/src/cpp/histogram.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -DDEBUG -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/cpp/histogram.cpp
g++ -o build-scons/src/cpp/interface.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -DDEBUG -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/cpp/interface.cpp
g++ -o build-scons/src/cpp/discrete_parametric.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -DDEBUG -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/cpp/discrete_parametric.cpp
g++ -o build-scons/src/cpp/vector_distance.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -DDEBUG -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/cpp/vector_distance.cpp
g++ -o build-scons/src/cpp/convolution.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -DDEBUG -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/cpp/convolution.cpp
g++ -o build-scons/src/cpp/plotable.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -DDEBUG -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/cpp/plotable.cpp
g++ -o build-scons/src/cpp/continuous_parametric_process.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -DDEBUG -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/cpp/continuous_parametric_process.cpp
g++ -o build-scons/lib/libvpstat_tool.so -shared build-scons/src/cpp/categorical_process.os build-scons/src/cpp/regression.os build-scons/src/cpp/compound.os build-scons/src/cpp/stat_label.os build-scons/src/cpp/mixture_algorithms.os build-scons/src/cpp/distribution.os build-scons/src/cpp/test.os build-scons/src/cpp/distance_matrix.os build-scons/src/cpp/chain.os build-scons/src/cpp/vector_algorithms.os build-scons/src/cpp/vectors.os build-scons/src/cpp/compound_algorithms.os build-scons/src/cpp/curves.os build-scons/src/cpp/continuous_parametric.os build-scons/src/cpp/discrete_parametric_process.os build-scons/src/cpp/convolution_algorithms.os build-scons/src/cpp/distribution_algorithms.os build-scons/src/cpp/discrete_mixture_algorithms.os build-scons/src/cpp/multivariate_mixture.os build-scons/src/cpp/mixture.os build-scons/src/cpp/multivariate_mixture_algorithms.os build-scons/src/cpp/dendrogram.os build-scons/src/cpp/clusters.os build-scons/src/cpp/frequency_distribution2.os build-scons/src/cpp/chain_algorithms.os build-scons/src/cpp/discrete_mixture.os build-scons/src/cpp/frequency_distribution1.os build-scons/src/cpp/histogram.os build-scons/src/cpp/interface.os build-scons/src/cpp/discrete_parametric.os build-scons/src/cpp/vector_distance.os build-scons/src/cpp/convolution.os build-scons/src/cpp/plotable.os build-scons/src/cpp/continuous_parametric_process.os -Lbuild-scons/lib -L/usr/lib -L/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/lib -L/usr/lib -L/usr/local/openalea/lib -lpthread -lpython2.7 -lboost_python -lQtOpenGL -lQtGui -lQtCore -lvptool
g++ -o build-scons/src/wrapper/export_base.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/wrapper/export_base.cpp
g++ -o build-scons/src/wrapper/export_categorical_process.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/wrapper/export_categorical_process.cpp
g++ -o build-scons/src/wrapper/export_chain.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/wrapper/export_chain.cpp
g++ -o build-scons/src/wrapper/export_chain_reestimation.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/wrapper/export_chain_reestimation.cpp
g++ -o build-scons/src/wrapper/export_compound.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/wrapper/export_compound.cpp
g++ -o build-scons/src/wrapper/export_convolution.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/wrapper/export_convolution.cpp
g++ -o build-scons/src/wrapper/export_curves.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/wrapper/export_curves.cpp
g++ -o build-scons/src/wrapper/export_distance_matrix.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/wrapper/export_distance_matrix.cpp
g++ -o build-scons/src/wrapper/export_distribution.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/wrapper/export_distribution.cpp
g++ -o build-scons/src/wrapper/export_frequency_distribution.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/wrapper/export_frequency_distribution.cpp
g++ -o build-scons/src/wrapper/export_markovian.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/wrapper/export_markovian.cpp
g++ -o build-scons/src/wrapper/export_mixture.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/wrapper/export_mixture.cpp
g++ -o build-scons/src/wrapper/export_plotable.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/wrapper/export_plotable.cpp
g++ -o build-scons/src/wrapper/export_regression.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/wrapper/export_regression.cpp
g++ -o build-scons/src/wrapper/export_vectors.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/wrapper/export_vectors.cpp
g++ -o build-scons/src/wrapper/stat_tool_wrap.os -c -g -g -fPIC -ftemplate-depth-100 -DQT_GUI_LIB -DBOOST_PYTHON_DYNAMIC_LIB -DQT_SHARED -DMESSAGE -Ibuild-scons/include -I/usr/include -I/usr/include/python2.7 -I/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/include -I/usr/include -I/usr/local/openalea/include -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore build-scons/src/wrapper/stat_tool_wrap.cpp
g++ -o src/stat_tool/_stat_tool.so -shared -Wl,-Bsymbolic -Wl,-soname=_stat_tool.so build-scons/src/wrapper/export_frequency_distribution.os build-scons/src/wrapper/export_curves.os build-scons/src/wrapper/export_markovian.os build-scons/src/wrapper/export_chain_reestimation.os build-scons/src/wrapper/export_regression.os build-scons/src/wrapper/export_vectors.os build-scons/src/wrapper/export_distance_matrix.os build-scons/src/wrapper/export_convolution.os build-scons/src/wrapper/export_plotable.os build-scons/src/wrapper/export_mixture.os build-scons/src/wrapper/export_distribution.os build-scons/src/wrapper/export_compound.os build-scons/src/wrapper/stat_tool_wrap.os build-scons/src/wrapper/export_chain.os build-scons/src/wrapper/export_base.os build-scons/src/wrapper/export_categorical_process.os -Lbuild-scons/lib -L/usr/lib -L/home/bolivier/git/oculonimbus/ema/lib/vplants/tool/build-scons/lib -L/usr/lib -L/usr/local/openalea/lib -lpthread -lpython2.7 -lboost_python -lQtOpenGL -lQtGui -lQtCore -lvptool -lvpstat_tool
scons: done building targets.
